config:
  aws:region: ap-southeast-2
  aws:allowedAccountIds: ["239018584217"]
  app:awsAccountId: "239018584217"
  app:regionCode: "apse2"
  app:appName: "Monorepo Template"
  app:appCode: "mrt"
  app:pulumiBackendUrl: "https://app.pulumi.com/kheriox-technologies"
  app:logsRetentionDays: "7"