config:
  aws:region: ap-southeast-2
  aws:allowedAccountIds: ["975050249555"]
  app:awsAccountId: "975050249555"
  app:regionCode: "apse2"
  app:appName: "Luxuria Homes Admin"
  app:appCode: "lha"
  app:pulumiBackendUrl: "https://app.pulumi.com/admin-luxuriahomes-com-au"
  app:logsRetentionDays: "7"
  app:baseDomain: "luxuriahomes.com.au"
  app:hostedZoneId: "Z0269169345LCDXPGG23V"
  # Set via: pulumi config set --secret app:cdnPublicKey "$(cat cdn_public_key.pem)" --stack dev
  # app:cdnPublicKey: "<RSA 2048-bit public key PEM — set as a Pulumi secret, do not commit the real value>"

  app:cdnPublicKey:
    secure: AAABAJro+2FkWfHpu+uez9tCJ/tul1CpJwLAQ3nSMz0kt6p6O/UPiX5GoJqV9tL0jJ+xI6O4v1Qegi5RGk9gXMvqCccDFod9VmWr/RFfNZTwowTngGjr5hkIuQccvo+8y/WdNbp8S3BkYJG/QW+mhlOj71wTiRS44vk405QPi9VJ7GTvCr9X+erKyRDpoNFgLIlxVDNKqzIbZellyYzvZ9dzPEysoXepsxi6U7eiv4YMeZJiSfUpBmHQUY5JHcnZen1cU+hCfWDcQdJ6EntomFD+9M4myXEBKutpDEjaR8W6QeQ5eifGVJbwPSFehJ69KS5O4a0pO1tjefjQNHzMHYeL8HpqGSRJ6bkevmXdB56kTCsdyWARUQoA8TGnRcQPk0aKmihwLzb2E/xDsSTstaSko1dOnhx3aF0fruHsQaeup6e0GLSZWKz8//RApmSMlBRlN+6RNX27M1MWM+8iFOL6fMsHcsPRtgqBOIQ1TirkFTS8oW+4E/mtCMeAllQAripUbrkf9oRFR5ApnDA/ueNSoqm0CrJxwQ8PmZjOn80CR3Tq6L/IB2I4GFgBUk/y746xM4hqioHAFkXX3OsAkZTwGLRkYfUzI7uw8FWhxcSWwPBpYxwG5N9QyQ1kTdtVoeY=
