config:
  aws:region: ap-southeast-2
  aws:allowedAccountIds: ["975050249555"]
  app:awsAccountId: "975050249555"
  app:regionCode: "apse2"
  app:appName: "Luxuria Homes Admin"
  app:appCode: "lha"
  app:pulumiBackendUrl: "https://app.pulumi.com/admin-luxuriahomes-com-au"
  app:logsRetentionDays: "7"
  app:baseDomain: "luxuriahomes.com.au"
  app:hostedZoneId: "Z0269169345LCDXPGG23V"
  # Set via: pulumi config set --secret app:cdnPublicKey "$(cat cdn_public_key.pem)" --stack prod
  # app:cdnPublicKey: "<RSA 2048-bit public key PEM — set as a Pulumi secret, do not commit the real value>"

  app:cdnPublicKey:
    secure: AAABAF1dSoGwNaF6eHV87f+ze10+PtilkpXaWIhVTo/e4YFC9+0mr7YufR0ffER+wx8f3drS/A3+5Qt53q1Z7oGNxhurt6VPRqOzPRaAj/flfHLtQPhQwaw6gEkVmwIEgeKtm6jnDCRb2mba74WwwMHqGRHwucNJH1QS5Qr3gwP7yr5+fzYOOkbvgJbAUAfcoAX728OeOfTpQD8wVymtwS2ZWSclpokNdqUQu9+fORDJhZ3GWfp28/MSqn8RuvxFBCCS/o7gfS6HIIZNvOhlCZWt3ARuUEAlfrPxDrWN3Ec3qholLh8aMsgnf6Bb/1b7m6wkx3utnRi83q/aWsvLHCH8AWEeDhlntpRMVWbtQLy/6tguDr2qkAlGeeZxAWDc3z+ULcMQ/i04FWXfsKWsp48UepCIYuYxoGuQVHAB0/6As9zzCuDqnfaCsANMozmzbgusMAeRGgyqzCT1C5nffeyjdWOF8wOBvNjjwi0iYCEQOo0HKm6VNyP2rCKs3MGoQv72jhoQQF27puLa+1FfRhmyBwRQGAqGdzFhM03qavyBbgp0xi+KJFER8erwpOhD7+z0iXyPgcvYnwncJKXgT0SkunFXF9mIJlhSkquPiJVeo9ssnPXZIY/oEgyYckw3Boo=
