/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as adminUsers_list from "../adminUsers/list.js";
import type * as adminUsers_replaceAll from "../adminUsers/replaceAll.js";
import type * as adminUsers_syncAdminUsers from "../adminUsers/syncAdminUsers.js";
import type * as adminUsers_syncNow from "../adminUsers/syncNow.js";
import type * as banners_backfillOrder from "../banners/backfillOrder.js";
import type * as banners_createFromMedia from "../banners/createFromMedia.js";
import type * as banners_get from "../banners/get.js";
import type * as banners_insert from "../banners/insert.js";
import type * as banners_list from "../banners/list.js";
import type * as banners_remove from "../banners/remove.js";
import type * as banners_removeRecord from "../banners/removeRecord.js";
import type * as banners_reorder from "../banners/reorder.js";
import type * as budgetTemplateItems_addItem from "../budgetTemplateItems/addItem.js";
import type * as budgetTemplateItems_listByTemplate from "../budgetTemplateItems/listByTemplate.js";
import type * as budgetTemplateItems_remove from "../budgetTemplateItems/remove.js";
import type * as budgetTemplateItems_setPrice from "../budgetTemplateItems/setPrice.js";
import type * as budgetTemplateItems_setPrices from "../budgetTemplateItems/setPrices.js";
import type * as budgetTemplates_add from "../budgetTemplates/add.js";
import type * as budgetTemplates_applyToProject from "../budgetTemplates/applyToProject.js";
import type * as budgetTemplates_get from "../budgetTemplates/get.js";
import type * as budgetTemplates_list from "../budgetTemplates/list.js";
import type * as budgetTemplates_remove from "../budgetTemplates/remove.js";
import type * as budgetTemplates_search from "../budgetTemplates/search.js";
import type * as budgetTemplates_shared from "../budgetTemplates/shared.js";
import type * as budgetTemplates_update from "../budgetTemplates/update.js";
import type * as cdn_signUrl from "../cdn/signUrl.js";
import type * as clientPortal_cdn_signUrl from "../clientPortal/cdn/signUrl.js";
import type * as clientPortal_documents_create from "../clientPortal/documents/create.js";
import type * as clientPortal_documents_generateUploadUrl from "../clientPortal/documents/generateUploadUrl.js";
import type * as clientPortal_documents_list from "../clientPortal/documents/list.js";
import type * as clientPortal_documents_shared from "../clientPortal/documents/shared.js";
import type * as clientPortal_grantAccess from "../clientPortal/grantAccess.js";
import type * as clientPortal_inclusions_appendNote from "../clientPortal/inclusions/appendNote.js";
import type * as clientPortal_inclusions_deleteNote from "../clientPortal/inclusions/deleteNote.js";
import type * as clientPortal_inclusions_generateNoteImageUploadUrl from "../clientPortal/inclusions/generateNoteImageUploadUrl.js";
import type * as clientPortal_inclusions_generatePdf from "../clientPortal/inclusions/generatePdf.js";
import type * as clientPortal_inclusions_list from "../clientPortal/inclusions/list.js";
import type * as clientPortal_inclusions_listNotes from "../clientPortal/inclusions/listNotes.js";
import type * as clientPortal_inclusions_setStatus from "../clientPortal/inclusions/setStatus.js";
import type * as clientPortal_internal from "../clientPortal/internal.js";
import type * as clientPortal_projects_get from "../clientPortal/projects/get.js";
import type * as clientPortal_projects_list from "../clientPortal/projects/list.js";
import type * as clientPortal_revokeAccess from "../clientPortal/revokeAccess.js";
import type * as companyDocuments_create from "../companyDocuments/create.js";
import type * as companyDocuments_createFolder from "../companyDocuments/createFolder.js";
import type * as companyDocuments_deleteFolder from "../companyDocuments/deleteFolder.js";
import type * as companyDocuments_ensureFolder from "../companyDocuments/ensureFolder.js";
import type * as companyDocuments_generateUploadUrl from "../companyDocuments/generateUploadUrl.js";
import type * as companyDocuments_listContents from "../companyDocuments/listContents.js";
import type * as companyDocuments_move from "../companyDocuments/move.js";
import type * as companyDocuments_remove from "../companyDocuments/remove.js";
import type * as companyDocuments_rename from "../companyDocuments/rename.js";
import type * as companyDocuments_renameFolder from "../companyDocuments/renameFolder.js";
import type * as companyDocuments_shared from "../companyDocuments/shared.js";
import type * as crons from "../crons.js";
import type * as dashboard_scheduleOverview from "../dashboard/scheduleOverview.js";
import type * as documentFolders_add from "../documentFolders/add.js";
import type * as documentFolders_addMany from "../documentFolders/addMany.js";
import type * as documentFolders_backfillBillsFolder from "../documentFolders/backfillBillsFolder.js";
import type * as documentFolders_backfillXeroBillsFolder from "../documentFolders/backfillXeroBillsFolder.js";
import type * as documentFolders_get from "../documentFolders/get.js";
import type * as documentFolders_lib_seedFolders from "../documentFolders/lib/seedFolders.js";
import type * as documentFolders_list from "../documentFolders/list.js";
import type * as documentFolders_remove from "../documentFolders/remove.js";
import type * as documentFolders_runXeroBillsBackfill from "../documentFolders/runXeroBillsBackfill.js";
import type * as documentFolders_search from "../documentFolders/search.js";
import type * as documentFolders_seed from "../documentFolders/seed.js";
import type * as documentFolders_seedProjectFolders from "../documentFolders/seedProjectFolders.js";
import type * as documentFolders_shared from "../documentFolders/shared.js";
import type * as documentFolders_update from "../documentFolders/update.js";
import type * as email_logSent from "../email/logSent.js";
import type * as email_notifyEnquiry from "../email/notifyEnquiry.js";
import type * as email_send from "../email/send.js";
import type * as email_shared from "../email/shared.js";
import type * as email_template from "../email/template.js";
import type * as emailSignatures_add from "../emailSignatures/add.js";
import type * as emailSignatures_get from "../emailSignatures/get.js";
import type * as emailSignatures_list from "../emailSignatures/list.js";
import type * as emailSignatures_remove from "../emailSignatures/remove.js";
import type * as emailSignatures_shared from "../emailSignatures/shared.js";
import type * as emailSignatures_update from "../emailSignatures/update.js";
import type * as emailTemplates_add from "../emailTemplates/add.js";
import type * as emailTemplates_get from "../emailTemplates/get.js";
import type * as emailTemplates_list from "../emailTemplates/list.js";
import type * as emailTemplates_remove from "../emailTemplates/remove.js";
import type * as emailTemplates_shared from "../emailTemplates/shared.js";
import type * as emailTemplates_update from "../emailTemplates/update.js";
import type * as fileStorage_deleteStorage from "../fileStorage/deleteStorage.js";
import type * as fileStorage_generateS3UploadUrl from "../fileStorage/generateS3UploadUrl.js";
import type * as fileStorage_generateUploadUrl from "../fileStorage/generateUploadUrl.js";
import type * as fileStorage_resolvePublicUrl from "../fileStorage/resolvePublicUrl.js";
import type * as gmailAddon_actions from "../gmailAddon/actions.js";
import type * as gmailAddon_handlers from "../gmailAddon/handlers.js";
import type * as gmailAddon_mutations from "../gmailAddon/mutations.js";
import type * as gmailAddon_queries from "../gmailAddon/queries.js";
import type * as http from "../http.js";
import type * as inclusionCategories_add from "../inclusionCategories/add.js";
import type * as inclusionCategories_list from "../inclusionCategories/list.js";
import type * as inclusionCategories_remove from "../inclusionCategories/remove.js";
import type * as inclusionCategories_search from "../inclusionCategories/search.js";
import type * as inclusionCategories_shared from "../inclusionCategories/shared.js";
import type * as inclusionCategories_update from "../inclusionCategories/update.js";
import type * as inclusionVariants_add from "../inclusionVariants/add.js";
import type * as inclusionVariants_getUnit from "../inclusionVariants/getUnit.js";
import type * as inclusionVariants_listByInclusion from "../inclusionVariants/listByInclusion.js";
import type * as inclusionVariants_migrateImageBinariesToS3 from "../inclusionVariants/migrateImageBinariesToS3.js";
import type * as inclusionVariants_migrateImageHelpers from "../inclusionVariants/migrateImageHelpers.js";
import type * as inclusionVariants_migrateImagesToS3 from "../inclusionVariants/migrateImagesToS3.js";
import type * as inclusionVariants_remove from "../inclusionVariants/remove.js";
import type * as inclusionVariants_search from "../inclusionVariants/search.js";
import type * as inclusionVariants_shared from "../inclusionVariants/shared.js";
import type * as inclusionVariants_update from "../inclusionVariants/update.js";
import type * as inclusions_add from "../inclusions/add.js";
import type * as inclusions_backfillSearchText from "../inclusions/backfillSearchText.js";
import type * as inclusions_get from "../inclusions/get.js";
import type * as inclusions_list from "../inclusions/list.js";
import type * as inclusions_remove from "../inclusions/remove.js";
import type * as inclusions_search from "../inclusions/search.js";
import type * as inclusions_shared from "../inclusions/shared.js";
import type * as inclusions_update from "../inclusions/update.js";
import type * as leads_list from "../leads/list.js";
import type * as leads_updateReadStatus from "../leads/updateReadStatus.js";
import type * as lib_buildSearchText from "../lib/buildSearchText.js";
import type * as lib_checkIdentity from "../lib/checkIdentity.js";
import type * as lib_clerk from "../lib/clerk.js";
import type * as lib_clientAccess from "../lib/clientAccess.js";
import type * as lib_logger from "../lib/logger.js";
import type * as lib_permissions from "../lib/permissions.js";
import type * as lib_toKebabCase from "../lib/toKebabCase.js";
import type * as locations_add from "../locations/add.js";
import type * as locations_addMany from "../locations/addMany.js";
import type * as locations_get from "../locations/get.js";
import type * as locations_list from "../locations/list.js";
import type * as locations_remove from "../locations/remove.js";
import type * as locations_search from "../locations/search.js";
import type * as locations_seed from "../locations/seed.js";
import type * as locations_shared from "../locations/shared.js";
import type * as locations_update from "../locations/update.js";
import type * as materialColors_add from "../materialColors/add.js";
import type * as materialColors_addMany from "../materialColors/addMany.js";
import type * as materialColors_get from "../materialColors/get.js";
import type * as materialColors_list from "../materialColors/list.js";
import type * as materialColors_remove from "../materialColors/remove.js";
import type * as materialColors_search from "../materialColors/search.js";
import type * as materialColors_seed from "../materialColors/seed.js";
import type * as materialColors_shared from "../materialColors/shared.js";
import type * as materialColors_update from "../materialColors/update.js";
import type * as materialItems_add from "../materialItems/add.js";
import type * as materialItems_listByMaterial from "../materialItems/listByMaterial.js";
import type * as materialItems_remove from "../materialItems/remove.js";
import type * as materialItems_shared from "../materialItems/shared.js";
import type * as materialItems_update from "../materialItems/update.js";
import type * as materials_add from "../materials/add.js";
import type * as materials_addToProject from "../materials/addToProject.js";
import type * as materials_get from "../materials/get.js";
import type * as materials_list from "../materials/list.js";
import type * as materials_remove from "../materials/remove.js";
import type * as materials_search from "../materials/search.js";
import type * as materials_shared from "../materials/shared.js";
import type * as materials_update from "../materials/update.js";
import type * as migration_exportScheduleTemplates from "../migration/exportScheduleTemplates.js";
import type * as migration_importScheduleTemplate from "../migration/importScheduleTemplate.js";
import type * as notifications_list from "../notifications/list.js";
import type * as notifications_listUnread from "../notifications/listUnread.js";
import type * as notifications_markAllRead from "../notifications/markAllRead.js";
import type * as notifications_markRead from "../notifications/markRead.js";
import type * as notifications_shared from "../notifications/shared.js";
import type * as notifications_unreadCount from "../notifications/unreadCount.js";
import type * as permissions_getEffectiveForRoles from "../permissions/getEffectiveForRoles.js";
import type * as permissions_list from "../permissions/list.js";
import type * as permissions_listRoleNames from "../permissions/listRoleNames.js";
import type * as permissions_removeRole from "../permissions/removeRole.js";
import type * as permissions_upsertRole from "../permissions/upsertRole.js";
import type * as projectBudgets_addItem from "../projectBudgets/addItem.js";
import type * as projectBudgets_clearPayments from "../projectBudgets/clearPayments.js";
import type * as projectBudgets_projectSummary from "../projectBudgets/projectSummary.js";
import type * as projectBudgets_remove from "../projectBudgets/remove.js";
import type * as projectBudgets_setPrices from "../projectBudgets/setPrices.js";
import type * as projectBudgets_tradeSummary from "../projectBudgets/tradeSummary.js";
import type * as projectBudgets_updatePrice from "../projectBudgets/updatePrice.js";
import type * as projectDocuments_create from "../projectDocuments/create.js";
import type * as projectDocuments_createFolder from "../projectDocuments/createFolder.js";
import type * as projectDocuments_deleteFolder from "../projectDocuments/deleteFolder.js";
import type * as projectDocuments_ensureFolder from "../projectDocuments/ensureFolder.js";
import type * as projectDocuments_generateUploadUrl from "../projectDocuments/generateUploadUrl.js";
import type * as projectDocuments_listContents from "../projectDocuments/listContents.js";
import type * as projectDocuments_move from "../projectDocuments/move.js";
import type * as projectDocuments_remove from "../projectDocuments/remove.js";
import type * as projectDocuments_rename from "../projectDocuments/rename.js";
import type * as projectDocuments_renameFolder from "../projectDocuments/renameFolder.js";
import type * as projectDocuments_setClientPortalVisibility from "../projectDocuments/setClientPortalVisibility.js";
import type * as projectDocuments_setFolderClientPortalVisibility from "../projectDocuments/setFolderClientPortalVisibility.js";
import type * as projectDocuments_shared from "../projectDocuments/shared.js";
import type * as projectInclusions_add from "../projectInclusions/add.js";
import type * as projectInclusions_appendNote from "../projectInclusions/appendNote.js";
import type * as projectInclusions_backfillSearchText from "../projectInclusions/backfillSearchText.js";
import type * as projectInclusions_clearOrphanedOrderRefs from "../projectInclusions/clearOrphanedOrderRefs.js";
import type * as projectInclusions_deleteNote from "../projectInclusions/deleteNote.js";
import type * as projectInclusions_generateNoteImageUploadUrl from "../projectInclusions/generateNoteImageUploadUrl.js";
import type * as projectInclusions_generatePdf from "../projectInclusions/generatePdf.js";
import type * as projectInclusions_list from "../projectInclusions/list.js";
import type * as projectInclusions_listNotes from "../projectInclusions/listNotes.js";
import type * as projectInclusions_migrateImageBinariesToS3 from "../projectInclusions/migrateImageBinariesToS3.js";
import type * as projectInclusions_migrateImageHelpers from "../projectInclusions/migrateImageHelpers.js";
import type * as projectInclusions_migrateImagesToS3 from "../projectInclusions/migrateImagesToS3.js";
import type * as projectInclusions_pdf_docDefinition from "../projectInclusions/pdf/docDefinition.js";
import type * as projectInclusions_pdf_logo from "../projectInclusions/pdf/logo.js";
import type * as projectInclusions_pdf_render from "../projectInclusions/pdf/render.js";
import type * as projectInclusions_remove from "../projectInclusions/remove.js";
import type * as projectInclusions_search from "../projectInclusions/search.js";
import type * as projectInclusions_shared from "../projectInclusions/shared.js";
import type * as projectInclusions_update from "../projectInclusions/update.js";
import type * as projectOrderTasks_add from "../projectOrderTasks/add.js";
import type * as projectOrderTasks_listByProject from "../projectOrderTasks/listByProject.js";
import type * as projectOrderTasks_remove from "../projectOrderTasks/remove.js";
import type * as projectOrderTasks_shared from "../projectOrderTasks/shared.js";
import type * as projectOrderTasks_update from "../projectOrderTasks/update.js";
import type * as projectOrders_add from "../projectOrders/add.js";
import type * as projectOrders_appendNote from "../projectOrders/appendNote.js";
import type * as projectOrders_clearOrderTradeId from "../projectOrders/clearOrderTradeId.js";
import type * as projectOrders_deleteNote from "../projectOrders/deleteNote.js";
import type * as projectOrders_generatePdf from "../projectOrders/generatePdf.js";
import type * as projectOrders_get from "../projectOrders/get.js";
import type * as projectOrders_getByRef from "../projectOrders/getByRef.js";
import type * as projectOrders_linkOrderTask from "../projectOrders/linkOrderTask.js";
import type * as projectOrders_list from "../projectOrders/list.js";
import type * as projectOrders_listNotes from "../projectOrders/listNotes.js";
import type * as projectOrders_listStatusHistory from "../projectOrders/listStatusHistory.js";
import type * as projectOrders_pdf_docDefinition from "../projectOrders/pdf/docDefinition.js";
import type * as projectOrders_remove from "../projectOrders/remove.js";
import type * as projectOrders_shared from "../projectOrders/shared.js";
import type * as projectOrders_update from "../projectOrders/update.js";
import type * as projectQuotations_add from "../projectQuotations/add.js";
import type * as projectQuotations_appendNote from "../projectQuotations/appendNote.js";
import type * as projectQuotations_approve from "../projectQuotations/approve.js";
import type * as projectQuotations_deleteNote from "../projectQuotations/deleteNote.js";
import type * as projectQuotations_generateUploadUrl from "../projectQuotations/generateUploadUrl.js";
import type * as projectQuotations_listByProject from "../projectQuotations/listByProject.js";
import type * as projectQuotations_listNotes from "../projectQuotations/listNotes.js";
import type * as projectQuotations_reject from "../projectQuotations/reject.js";
import type * as projectQuotations_remove from "../projectQuotations/remove.js";
import type * as projectQuotations_shared from "../projectQuotations/shared.js";
import type * as projectQuotations_update from "../projectQuotations/update.js";
import type * as projectServiceProviders_add from "../projectServiceProviders/add.js";
import type * as projectServiceProviders_listByProject from "../projectServiceProviders/listByProject.js";
import type * as projectServiceProviders_remove from "../projectServiceProviders/remove.js";
import type * as projectStages_add from "../projectStages/add.js";
import type * as projectStages_clearDependency from "../projectStages/clearDependency.js";
import type * as projectStages_listByProject from "../projectStages/listByProject.js";
import type * as projectStages_remove from "../projectStages/remove.js";
import type * as projectStages_reorder from "../projectStages/reorder.js";
import type * as projectStages_shared from "../projectStages/shared.js";
import type * as projectStages_update from "../projectStages/update.js";
import type * as projectStages_updateDates from "../projectStages/updateDates.js";
import type * as projectStages_updateStatus from "../projectStages/updateStatus.js";
import type * as projectTasks_add from "../projectTasks/add.js";
import type * as projectTasks_clearDependency from "../projectTasks/clearDependency.js";
import type * as projectTasks_listByProject from "../projectTasks/listByProject.js";
import type * as projectTasks_listByStage from "../projectTasks/listByStage.js";
import type * as projectTasks_remove from "../projectTasks/remove.js";
import type * as projectTasks_reorder from "../projectTasks/reorder.js";
import type * as projectTasks_shared from "../projectTasks/shared.js";
import type * as projectTasks_update from "../projectTasks/update.js";
import type * as projectTasks_updateDates from "../projectTasks/updateDates.js";
import type * as projectTasks_updateStatus from "../projectTasks/updateStatus.js";
import type * as projects_add from "../projects/add.js";
import type * as projects_applyXeroFinancials from "../projects/applyXeroFinancials.js";
import type * as projects_get from "../projects/get.js";
import type * as projects_list from "../projects/list.js";
import type * as projects_listXeroMapped from "../projects/listXeroMapped.js";
import type * as projects_remove from "../projects/remove.js";
import type * as projects_search from "../projects/search.js";
import type * as projects_shared from "../projects/shared.js";
import type * as projects_update from "../projects/update.js";
import type * as scheduleOrderTasks_add from "../scheduleOrderTasks/add.js";
import type * as scheduleOrderTasks_listByTemplate from "../scheduleOrderTasks/listByTemplate.js";
import type * as scheduleOrderTasks_remove from "../scheduleOrderTasks/remove.js";
import type * as scheduleOrderTasks_shared from "../scheduleOrderTasks/shared.js";
import type * as scheduleOrderTasks_update from "../scheduleOrderTasks/update.js";
import type * as scheduleStages_add from "../scheduleStages/add.js";
import type * as scheduleStages_backfillOffsetDays from "../scheduleStages/backfillOffsetDays.js";
import type * as scheduleStages_backfillOrder from "../scheduleStages/backfillOrder.js";
import type * as scheduleStages_clearDependency from "../scheduleStages/clearDependency.js";
import type * as scheduleStages_listByTemplate from "../scheduleStages/listByTemplate.js";
import type * as scheduleStages_remove from "../scheduleStages/remove.js";
import type * as scheduleStages_reorder from "../scheduleStages/reorder.js";
import type * as scheduleStages_shared from "../scheduleStages/shared.js";
import type * as scheduleStages_update from "../scheduleStages/update.js";
import type * as scheduleStages_updateOffset from "../scheduleStages/updateOffset.js";
import type * as scheduleTasks_add from "../scheduleTasks/add.js";
import type * as scheduleTasks_backfillOffsetDays from "../scheduleTasks/backfillOffsetDays.js";
import type * as scheduleTasks_backfillOrder from "../scheduleTasks/backfillOrder.js";
import type * as scheduleTasks_clearDependency from "../scheduleTasks/clearDependency.js";
import type * as scheduleTasks_listByStage from "../scheduleTasks/listByStage.js";
import type * as scheduleTasks_listByTemplate from "../scheduleTasks/listByTemplate.js";
import type * as scheduleTasks_remove from "../scheduleTasks/remove.js";
import type * as scheduleTasks_reorder from "../scheduleTasks/reorder.js";
import type * as scheduleTasks_shared from "../scheduleTasks/shared.js";
import type * as scheduleTasks_update from "../scheduleTasks/update.js";
import type * as scheduleTasks_updateDuration from "../scheduleTasks/updateDuration.js";
import type * as scheduleTasks_updateOffset from "../scheduleTasks/updateOffset.js";
import type * as scheduleTemplates_add from "../scheduleTemplates/add.js";
import type * as scheduleTemplates_applyToProject from "../scheduleTemplates/applyToProject.js";
import type * as scheduleTemplates_get from "../scheduleTemplates/get.js";
import type * as scheduleTemplates_list from "../scheduleTemplates/list.js";
import type * as scheduleTemplates_remove from "../scheduleTemplates/remove.js";
import type * as scheduleTemplates_search from "../scheduleTemplates/search.js";
import type * as scheduleTemplates_seed from "../scheduleTemplates/seed.js";
import type * as scheduleTemplates_shared from "../scheduleTemplates/shared.js";
import type * as scheduleTemplates_update from "../scheduleTemplates/update.js";
import type * as serviceProviders_add from "../serviceProviders/add.js";
import type * as serviceProviders_backfillSearchText from "../serviceProviders/backfillSearchText.js";
import type * as serviceProviders_get from "../serviceProviders/get.js";
import type * as serviceProviders_list from "../serviceProviders/list.js";
import type * as serviceProviders_remove from "../serviceProviders/remove.js";
import type * as serviceProviders_search from "../serviceProviders/search.js";
import type * as serviceProviders_seed from "../serviceProviders/seed.js";
import type * as serviceProviders_shared from "../serviceProviders/shared.js";
import type * as serviceProviders_update from "../serviceProviders/update.js";
import type * as takeoffCategories_add from "../takeoffCategories/add.js";
import type * as takeoffCategories_addMany from "../takeoffCategories/addMany.js";
import type * as takeoffCategories_get from "../takeoffCategories/get.js";
import type * as takeoffCategories_list from "../takeoffCategories/list.js";
import type * as takeoffCategories_remove from "../takeoffCategories/remove.js";
import type * as takeoffCategories_search from "../takeoffCategories/search.js";
import type * as takeoffCategories_shared from "../takeoffCategories/shared.js";
import type * as takeoffCategories_update from "../takeoffCategories/update.js";
import type * as takeoffs_addToTakeoffs from "../takeoffs/addToTakeoffs.js";
import type * as takeoffs_get from "../takeoffs/get.js";
import type * as takeoffs_list from "../takeoffs/list.js";
import type * as takeoffs_remove from "../takeoffs/remove.js";
import type * as takeoffs_rename from "../takeoffs/rename.js";
import type * as takeoffs_save from "../takeoffs/save.js";
import type * as takeoffs_shared from "../takeoffs/shared.js";
import type * as tasks_add from "../tasks/add.js";
import type * as tasks_appendNote from "../tasks/appendNote.js";
import type * as tasks_deleteNote from "../tasks/deleteNote.js";
import type * as tasks_list from "../tasks/list.js";
import type * as tasks_listNotes from "../tasks/listNotes.js";
import type * as tasks_remove from "../tasks/remove.js";
import type * as tasks_shared from "../tasks/shared.js";
import type * as tasks_update from "../tasks/update.js";
import type * as tasks_updateStatus from "../tasks/updateStatus.js";
import type * as tradeStages_add from "../tradeStages/add.js";
import type * as tradeStages_list from "../tradeStages/list.js";
import type * as tradeStages_remove from "../tradeStages/remove.js";
import type * as tradeStages_reorder from "../tradeStages/reorder.js";
import type * as tradeStages_shared from "../tradeStages/shared.js";
import type * as tradeStages_update from "../tradeStages/update.js";
import type * as trades_add from "../trades/add.js";
import type * as trades_addMany from "../trades/addMany.js";
import type * as trades_get from "../trades/get.js";
import type * as trades_list from "../trades/list.js";
import type * as trades_listXeroAssignments from "../trades/listXeroAssignments.js";
import type * as trades_remove from "../trades/remove.js";
import type * as trades_reorderTrades from "../trades/reorderTrades.js";
import type * as trades_search from "../trades/search.js";
import type * as trades_seed from "../trades/seed.js";
import type * as trades_shared from "../trades/shared.js";
import type * as trades_update from "../trades/update.js";
import type * as units_list from "../units/list.js";
import type * as units_seed from "../units/seed.js";
import type * as users_create from "../users/create.js";
import type * as users_list from "../users/list.js";
import type * as users_remove from "../users/remove.js";
import type * as users_setRoles from "../users/setRoles.js";
import type * as users_update from "../users/update.js";
import type * as vendors_add from "../vendors/add.js";
import type * as vendors_addMany from "../vendors/addMany.js";
import type * as vendors_get from "../vendors/get.js";
import type * as vendors_list from "../vendors/list.js";
import type * as vendors_remove from "../vendors/remove.js";
import type * as vendors_search from "../vendors/search.js";
import type * as vendors_seed from "../vendors/seed.js";
import type * as vendors_shared from "../vendors/shared.js";
import type * as vendors_update from "../vendors/update.js";
import type * as web_banners from "../web/banners.js";
import type * as web_leads from "../web/leads.js";
import type * as web_projects from "../web/projects.js";
import type * as web_shared from "../web/shared.js";
import type * as websiteProjects_add from "../websiteProjects/add.js";
import type * as websiteProjects_appendMedia from "../websiteProjects/appendMedia.js";
import type * as websiteProjects_deleteMedia from "../websiteProjects/deleteMedia.js";
import type * as websiteProjects_generateUploadUrl from "../websiteProjects/generateUploadUrl.js";
import type * as websiteProjects_get from "../websiteProjects/get.js";
import type * as websiteProjects_list from "../websiteProjects/list.js";
import type * as websiteProjects_remove from "../websiteProjects/remove.js";
import type * as websiteProjects_removeMediaEntry from "../websiteProjects/removeMediaEntry.js";
import type * as websiteProjects_setMainImage from "../websiteProjects/setMainImage.js";
import type * as websiteProjects_shared from "../websiteProjects/shared.js";
import type * as websiteProjects_update from "../websiteProjects/update.js";
import type * as xero_createAccount from "../xero/createAccount.js";
import type * as xero_emailBillToXero from "../xero/emailBillToXero.js";
import type * as xero_listAccounts from "../xero/listAccounts.js";
import type * as xero_listTrackingOptions from "../xero/listTrackingOptions.js";
import type * as xero_shared from "../xero/shared.js";
import type * as xero_syncProjectFinancials from "../xero/syncProjectFinancials.js";
import type * as xero_syncProjectFinancialsNow from "../xero/syncProjectFinancialsNow.js";
import type * as xero_testAccounts from "../xero/testAccounts.js";
import type * as xero_testConnection from "../xero/testConnection.js";
import type * as xero_testProfitAndLoss from "../xero/testProfitAndLoss.js";
import type * as xeroAccountActuals_apply from "../xeroAccountActuals/apply.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "adminUsers/list": typeof adminUsers_list;
  "adminUsers/replaceAll": typeof adminUsers_replaceAll;
  "adminUsers/syncAdminUsers": typeof adminUsers_syncAdminUsers;
  "adminUsers/syncNow": typeof adminUsers_syncNow;
  "banners/backfillOrder": typeof banners_backfillOrder;
  "banners/createFromMedia": typeof banners_createFromMedia;
  "banners/get": typeof banners_get;
  "banners/insert": typeof banners_insert;
  "banners/list": typeof banners_list;
  "banners/remove": typeof banners_remove;
  "banners/removeRecord": typeof banners_removeRecord;
  "banners/reorder": typeof banners_reorder;
  "budgetTemplateItems/addItem": typeof budgetTemplateItems_addItem;
  "budgetTemplateItems/listByTemplate": typeof budgetTemplateItems_listByTemplate;
  "budgetTemplateItems/remove": typeof budgetTemplateItems_remove;
  "budgetTemplateItems/setPrice": typeof budgetTemplateItems_setPrice;
  "budgetTemplateItems/setPrices": typeof budgetTemplateItems_setPrices;
  "budgetTemplates/add": typeof budgetTemplates_add;
  "budgetTemplates/applyToProject": typeof budgetTemplates_applyToProject;
  "budgetTemplates/get": typeof budgetTemplates_get;
  "budgetTemplates/list": typeof budgetTemplates_list;
  "budgetTemplates/remove": typeof budgetTemplates_remove;
  "budgetTemplates/search": typeof budgetTemplates_search;
  "budgetTemplates/shared": typeof budgetTemplates_shared;
  "budgetTemplates/update": typeof budgetTemplates_update;
  "cdn/signUrl": typeof cdn_signUrl;
  "clientPortal/cdn/signUrl": typeof clientPortal_cdn_signUrl;
  "clientPortal/documents/create": typeof clientPortal_documents_create;
  "clientPortal/documents/generateUploadUrl": typeof clientPortal_documents_generateUploadUrl;
  "clientPortal/documents/list": typeof clientPortal_documents_list;
  "clientPortal/documents/shared": typeof clientPortal_documents_shared;
  "clientPortal/grantAccess": typeof clientPortal_grantAccess;
  "clientPortal/inclusions/appendNote": typeof clientPortal_inclusions_appendNote;
  "clientPortal/inclusions/deleteNote": typeof clientPortal_inclusions_deleteNote;
  "clientPortal/inclusions/generateNoteImageUploadUrl": typeof clientPortal_inclusions_generateNoteImageUploadUrl;
  "clientPortal/inclusions/generatePdf": typeof clientPortal_inclusions_generatePdf;
  "clientPortal/inclusions/list": typeof clientPortal_inclusions_list;
  "clientPortal/inclusions/listNotes": typeof clientPortal_inclusions_listNotes;
  "clientPortal/inclusions/setStatus": typeof clientPortal_inclusions_setStatus;
  "clientPortal/internal": typeof clientPortal_internal;
  "clientPortal/projects/get": typeof clientPortal_projects_get;
  "clientPortal/projects/list": typeof clientPortal_projects_list;
  "clientPortal/revokeAccess": typeof clientPortal_revokeAccess;
  "companyDocuments/create": typeof companyDocuments_create;
  "companyDocuments/createFolder": typeof companyDocuments_createFolder;
  "companyDocuments/deleteFolder": typeof companyDocuments_deleteFolder;
  "companyDocuments/ensureFolder": typeof companyDocuments_ensureFolder;
  "companyDocuments/generateUploadUrl": typeof companyDocuments_generateUploadUrl;
  "companyDocuments/listContents": typeof companyDocuments_listContents;
  "companyDocuments/move": typeof companyDocuments_move;
  "companyDocuments/remove": typeof companyDocuments_remove;
  "companyDocuments/rename": typeof companyDocuments_rename;
  "companyDocuments/renameFolder": typeof companyDocuments_renameFolder;
  "companyDocuments/shared": typeof companyDocuments_shared;
  crons: typeof crons;
  "dashboard/scheduleOverview": typeof dashboard_scheduleOverview;
  "documentFolders/add": typeof documentFolders_add;
  "documentFolders/addMany": typeof documentFolders_addMany;
  "documentFolders/backfillBillsFolder": typeof documentFolders_backfillBillsFolder;
  "documentFolders/backfillXeroBillsFolder": typeof documentFolders_backfillXeroBillsFolder;
  "documentFolders/get": typeof documentFolders_get;
  "documentFolders/lib/seedFolders": typeof documentFolders_lib_seedFolders;
  "documentFolders/list": typeof documentFolders_list;
  "documentFolders/remove": typeof documentFolders_remove;
  "documentFolders/runXeroBillsBackfill": typeof documentFolders_runXeroBillsBackfill;
  "documentFolders/search": typeof documentFolders_search;
  "documentFolders/seed": typeof documentFolders_seed;
  "documentFolders/seedProjectFolders": typeof documentFolders_seedProjectFolders;
  "documentFolders/shared": typeof documentFolders_shared;
  "documentFolders/update": typeof documentFolders_update;
  "email/logSent": typeof email_logSent;
  "email/notifyEnquiry": typeof email_notifyEnquiry;
  "email/send": typeof email_send;
  "email/shared": typeof email_shared;
  "email/template": typeof email_template;
  "emailSignatures/add": typeof emailSignatures_add;
  "emailSignatures/get": typeof emailSignatures_get;
  "emailSignatures/list": typeof emailSignatures_list;
  "emailSignatures/remove": typeof emailSignatures_remove;
  "emailSignatures/shared": typeof emailSignatures_shared;
  "emailSignatures/update": typeof emailSignatures_update;
  "emailTemplates/add": typeof emailTemplates_add;
  "emailTemplates/get": typeof emailTemplates_get;
  "emailTemplates/list": typeof emailTemplates_list;
  "emailTemplates/remove": typeof emailTemplates_remove;
  "emailTemplates/shared": typeof emailTemplates_shared;
  "emailTemplates/update": typeof emailTemplates_update;
  "fileStorage/deleteStorage": typeof fileStorage_deleteStorage;
  "fileStorage/generateS3UploadUrl": typeof fileStorage_generateS3UploadUrl;
  "fileStorage/generateUploadUrl": typeof fileStorage_generateUploadUrl;
  "fileStorage/resolvePublicUrl": typeof fileStorage_resolvePublicUrl;
  "gmailAddon/actions": typeof gmailAddon_actions;
  "gmailAddon/handlers": typeof gmailAddon_handlers;
  "gmailAddon/mutations": typeof gmailAddon_mutations;
  "gmailAddon/queries": typeof gmailAddon_queries;
  http: typeof http;
  "inclusionCategories/add": typeof inclusionCategories_add;
  "inclusionCategories/list": typeof inclusionCategories_list;
  "inclusionCategories/remove": typeof inclusionCategories_remove;
  "inclusionCategories/search": typeof inclusionCategories_search;
  "inclusionCategories/shared": typeof inclusionCategories_shared;
  "inclusionCategories/update": typeof inclusionCategories_update;
  "inclusionVariants/add": typeof inclusionVariants_add;
  "inclusionVariants/getUnit": typeof inclusionVariants_getUnit;
  "inclusionVariants/listByInclusion": typeof inclusionVariants_listByInclusion;
  "inclusionVariants/migrateImageBinariesToS3": typeof inclusionVariants_migrateImageBinariesToS3;
  "inclusionVariants/migrateImageHelpers": typeof inclusionVariants_migrateImageHelpers;
  "inclusionVariants/migrateImagesToS3": typeof inclusionVariants_migrateImagesToS3;
  "inclusionVariants/remove": typeof inclusionVariants_remove;
  "inclusionVariants/search": typeof inclusionVariants_search;
  "inclusionVariants/shared": typeof inclusionVariants_shared;
  "inclusionVariants/update": typeof inclusionVariants_update;
  "inclusions/add": typeof inclusions_add;
  "inclusions/backfillSearchText": typeof inclusions_backfillSearchText;
  "inclusions/get": typeof inclusions_get;
  "inclusions/list": typeof inclusions_list;
  "inclusions/remove": typeof inclusions_remove;
  "inclusions/search": typeof inclusions_search;
  "inclusions/shared": typeof inclusions_shared;
  "inclusions/update": typeof inclusions_update;
  "leads/list": typeof leads_list;
  "leads/updateReadStatus": typeof leads_updateReadStatus;
  "lib/buildSearchText": typeof lib_buildSearchText;
  "lib/checkIdentity": typeof lib_checkIdentity;
  "lib/clerk": typeof lib_clerk;
  "lib/clientAccess": typeof lib_clientAccess;
  "lib/logger": typeof lib_logger;
  "lib/permissions": typeof lib_permissions;
  "lib/toKebabCase": typeof lib_toKebabCase;
  "locations/add": typeof locations_add;
  "locations/addMany": typeof locations_addMany;
  "locations/get": typeof locations_get;
  "locations/list": typeof locations_list;
  "locations/remove": typeof locations_remove;
  "locations/search": typeof locations_search;
  "locations/seed": typeof locations_seed;
  "locations/shared": typeof locations_shared;
  "locations/update": typeof locations_update;
  "materialColors/add": typeof materialColors_add;
  "materialColors/addMany": typeof materialColors_addMany;
  "materialColors/get": typeof materialColors_get;
  "materialColors/list": typeof materialColors_list;
  "materialColors/remove": typeof materialColors_remove;
  "materialColors/search": typeof materialColors_search;
  "materialColors/seed": typeof materialColors_seed;
  "materialColors/shared": typeof materialColors_shared;
  "materialColors/update": typeof materialColors_update;
  "materialItems/add": typeof materialItems_add;
  "materialItems/listByMaterial": typeof materialItems_listByMaterial;
  "materialItems/remove": typeof materialItems_remove;
  "materialItems/shared": typeof materialItems_shared;
  "materialItems/update": typeof materialItems_update;
  "materials/add": typeof materials_add;
  "materials/addToProject": typeof materials_addToProject;
  "materials/get": typeof materials_get;
  "materials/list": typeof materials_list;
  "materials/remove": typeof materials_remove;
  "materials/search": typeof materials_search;
  "materials/shared": typeof materials_shared;
  "materials/update": typeof materials_update;
  "migration/exportScheduleTemplates": typeof migration_exportScheduleTemplates;
  "migration/importScheduleTemplate": typeof migration_importScheduleTemplate;
  "notifications/list": typeof notifications_list;
  "notifications/listUnread": typeof notifications_listUnread;
  "notifications/markAllRead": typeof notifications_markAllRead;
  "notifications/markRead": typeof notifications_markRead;
  "notifications/shared": typeof notifications_shared;
  "notifications/unreadCount": typeof notifications_unreadCount;
  "permissions/getEffectiveForRoles": typeof permissions_getEffectiveForRoles;
  "permissions/list": typeof permissions_list;
  "permissions/listRoleNames": typeof permissions_listRoleNames;
  "permissions/removeRole": typeof permissions_removeRole;
  "permissions/upsertRole": typeof permissions_upsertRole;
  "projectBudgets/addItem": typeof projectBudgets_addItem;
  "projectBudgets/clearPayments": typeof projectBudgets_clearPayments;
  "projectBudgets/projectSummary": typeof projectBudgets_projectSummary;
  "projectBudgets/remove": typeof projectBudgets_remove;
  "projectBudgets/setPrices": typeof projectBudgets_setPrices;
  "projectBudgets/tradeSummary": typeof projectBudgets_tradeSummary;
  "projectBudgets/updatePrice": typeof projectBudgets_updatePrice;
  "projectDocuments/create": typeof projectDocuments_create;
  "projectDocuments/createFolder": typeof projectDocuments_createFolder;
  "projectDocuments/deleteFolder": typeof projectDocuments_deleteFolder;
  "projectDocuments/ensureFolder": typeof projectDocuments_ensureFolder;
  "projectDocuments/generateUploadUrl": typeof projectDocuments_generateUploadUrl;
  "projectDocuments/listContents": typeof projectDocuments_listContents;
  "projectDocuments/move": typeof projectDocuments_move;
  "projectDocuments/remove": typeof projectDocuments_remove;
  "projectDocuments/rename": typeof projectDocuments_rename;
  "projectDocuments/renameFolder": typeof projectDocuments_renameFolder;
  "projectDocuments/setClientPortalVisibility": typeof projectDocuments_setClientPortalVisibility;
  "projectDocuments/setFolderClientPortalVisibility": typeof projectDocuments_setFolderClientPortalVisibility;
  "projectDocuments/shared": typeof projectDocuments_shared;
  "projectInclusions/add": typeof projectInclusions_add;
  "projectInclusions/appendNote": typeof projectInclusions_appendNote;
  "projectInclusions/backfillSearchText": typeof projectInclusions_backfillSearchText;
  "projectInclusions/clearOrphanedOrderRefs": typeof projectInclusions_clearOrphanedOrderRefs;
  "projectInclusions/deleteNote": typeof projectInclusions_deleteNote;
  "projectInclusions/generateNoteImageUploadUrl": typeof projectInclusions_generateNoteImageUploadUrl;
  "projectInclusions/generatePdf": typeof projectInclusions_generatePdf;
  "projectInclusions/list": typeof projectInclusions_list;
  "projectInclusions/listNotes": typeof projectInclusions_listNotes;
  "projectInclusions/migrateImageBinariesToS3": typeof projectInclusions_migrateImageBinariesToS3;
  "projectInclusions/migrateImageHelpers": typeof projectInclusions_migrateImageHelpers;
  "projectInclusions/migrateImagesToS3": typeof projectInclusions_migrateImagesToS3;
  "projectInclusions/pdf/docDefinition": typeof projectInclusions_pdf_docDefinition;
  "projectInclusions/pdf/logo": typeof projectInclusions_pdf_logo;
  "projectInclusions/pdf/render": typeof projectInclusions_pdf_render;
  "projectInclusions/remove": typeof projectInclusions_remove;
  "projectInclusions/search": typeof projectInclusions_search;
  "projectInclusions/shared": typeof projectInclusions_shared;
  "projectInclusions/update": typeof projectInclusions_update;
  "projectOrderTasks/add": typeof projectOrderTasks_add;
  "projectOrderTasks/listByProject": typeof projectOrderTasks_listByProject;
  "projectOrderTasks/remove": typeof projectOrderTasks_remove;
  "projectOrderTasks/shared": typeof projectOrderTasks_shared;
  "projectOrderTasks/update": typeof projectOrderTasks_update;
  "projectOrders/add": typeof projectOrders_add;
  "projectOrders/appendNote": typeof projectOrders_appendNote;
  "projectOrders/clearOrderTradeId": typeof projectOrders_clearOrderTradeId;
  "projectOrders/deleteNote": typeof projectOrders_deleteNote;
  "projectOrders/generatePdf": typeof projectOrders_generatePdf;
  "projectOrders/get": typeof projectOrders_get;
  "projectOrders/getByRef": typeof projectOrders_getByRef;
  "projectOrders/linkOrderTask": typeof projectOrders_linkOrderTask;
  "projectOrders/list": typeof projectOrders_list;
  "projectOrders/listNotes": typeof projectOrders_listNotes;
  "projectOrders/listStatusHistory": typeof projectOrders_listStatusHistory;
  "projectOrders/pdf/docDefinition": typeof projectOrders_pdf_docDefinition;
  "projectOrders/remove": typeof projectOrders_remove;
  "projectOrders/shared": typeof projectOrders_shared;
  "projectOrders/update": typeof projectOrders_update;
  "projectQuotations/add": typeof projectQuotations_add;
  "projectQuotations/appendNote": typeof projectQuotations_appendNote;
  "projectQuotations/approve": typeof projectQuotations_approve;
  "projectQuotations/deleteNote": typeof projectQuotations_deleteNote;
  "projectQuotations/generateUploadUrl": typeof projectQuotations_generateUploadUrl;
  "projectQuotations/listByProject": typeof projectQuotations_listByProject;
  "projectQuotations/listNotes": typeof projectQuotations_listNotes;
  "projectQuotations/reject": typeof projectQuotations_reject;
  "projectQuotations/remove": typeof projectQuotations_remove;
  "projectQuotations/shared": typeof projectQuotations_shared;
  "projectQuotations/update": typeof projectQuotations_update;
  "projectServiceProviders/add": typeof projectServiceProviders_add;
  "projectServiceProviders/listByProject": typeof projectServiceProviders_listByProject;
  "projectServiceProviders/remove": typeof projectServiceProviders_remove;
  "projectStages/add": typeof projectStages_add;
  "projectStages/clearDependency": typeof projectStages_clearDependency;
  "projectStages/listByProject": typeof projectStages_listByProject;
  "projectStages/remove": typeof projectStages_remove;
  "projectStages/reorder": typeof projectStages_reorder;
  "projectStages/shared": typeof projectStages_shared;
  "projectStages/update": typeof projectStages_update;
  "projectStages/updateDates": typeof projectStages_updateDates;
  "projectStages/updateStatus": typeof projectStages_updateStatus;
  "projectTasks/add": typeof projectTasks_add;
  "projectTasks/clearDependency": typeof projectTasks_clearDependency;
  "projectTasks/listByProject": typeof projectTasks_listByProject;
  "projectTasks/listByStage": typeof projectTasks_listByStage;
  "projectTasks/remove": typeof projectTasks_remove;
  "projectTasks/reorder": typeof projectTasks_reorder;
  "projectTasks/shared": typeof projectTasks_shared;
  "projectTasks/update": typeof projectTasks_update;
  "projectTasks/updateDates": typeof projectTasks_updateDates;
  "projectTasks/updateStatus": typeof projectTasks_updateStatus;
  "projects/add": typeof projects_add;
  "projects/applyXeroFinancials": typeof projects_applyXeroFinancials;
  "projects/get": typeof projects_get;
  "projects/list": typeof projects_list;
  "projects/listXeroMapped": typeof projects_listXeroMapped;
  "projects/remove": typeof projects_remove;
  "projects/search": typeof projects_search;
  "projects/shared": typeof projects_shared;
  "projects/update": typeof projects_update;
  "scheduleOrderTasks/add": typeof scheduleOrderTasks_add;
  "scheduleOrderTasks/listByTemplate": typeof scheduleOrderTasks_listByTemplate;
  "scheduleOrderTasks/remove": typeof scheduleOrderTasks_remove;
  "scheduleOrderTasks/shared": typeof scheduleOrderTasks_shared;
  "scheduleOrderTasks/update": typeof scheduleOrderTasks_update;
  "scheduleStages/add": typeof scheduleStages_add;
  "scheduleStages/backfillOffsetDays": typeof scheduleStages_backfillOffsetDays;
  "scheduleStages/backfillOrder": typeof scheduleStages_backfillOrder;
  "scheduleStages/clearDependency": typeof scheduleStages_clearDependency;
  "scheduleStages/listByTemplate": typeof scheduleStages_listByTemplate;
  "scheduleStages/remove": typeof scheduleStages_remove;
  "scheduleStages/reorder": typeof scheduleStages_reorder;
  "scheduleStages/shared": typeof scheduleStages_shared;
  "scheduleStages/update": typeof scheduleStages_update;
  "scheduleStages/updateOffset": typeof scheduleStages_updateOffset;
  "scheduleTasks/add": typeof scheduleTasks_add;
  "scheduleTasks/backfillOffsetDays": typeof scheduleTasks_backfillOffsetDays;
  "scheduleTasks/backfillOrder": typeof scheduleTasks_backfillOrder;
  "scheduleTasks/clearDependency": typeof scheduleTasks_clearDependency;
  "scheduleTasks/listByStage": typeof scheduleTasks_listByStage;
  "scheduleTasks/listByTemplate": typeof scheduleTasks_listByTemplate;
  "scheduleTasks/remove": typeof scheduleTasks_remove;
  "scheduleTasks/reorder": typeof scheduleTasks_reorder;
  "scheduleTasks/shared": typeof scheduleTasks_shared;
  "scheduleTasks/update": typeof scheduleTasks_update;
  "scheduleTasks/updateDuration": typeof scheduleTasks_updateDuration;
  "scheduleTasks/updateOffset": typeof scheduleTasks_updateOffset;
  "scheduleTemplates/add": typeof scheduleTemplates_add;
  "scheduleTemplates/applyToProject": typeof scheduleTemplates_applyToProject;
  "scheduleTemplates/get": typeof scheduleTemplates_get;
  "scheduleTemplates/list": typeof scheduleTemplates_list;
  "scheduleTemplates/remove": typeof scheduleTemplates_remove;
  "scheduleTemplates/search": typeof scheduleTemplates_search;
  "scheduleTemplates/seed": typeof scheduleTemplates_seed;
  "scheduleTemplates/shared": typeof scheduleTemplates_shared;
  "scheduleTemplates/update": typeof scheduleTemplates_update;
  "serviceProviders/add": typeof serviceProviders_add;
  "serviceProviders/backfillSearchText": typeof serviceProviders_backfillSearchText;
  "serviceProviders/get": typeof serviceProviders_get;
  "serviceProviders/list": typeof serviceProviders_list;
  "serviceProviders/remove": typeof serviceProviders_remove;
  "serviceProviders/search": typeof serviceProviders_search;
  "serviceProviders/seed": typeof serviceProviders_seed;
  "serviceProviders/shared": typeof serviceProviders_shared;
  "serviceProviders/update": typeof serviceProviders_update;
  "takeoffCategories/add": typeof takeoffCategories_add;
  "takeoffCategories/addMany": typeof takeoffCategories_addMany;
  "takeoffCategories/get": typeof takeoffCategories_get;
  "takeoffCategories/list": typeof takeoffCategories_list;
  "takeoffCategories/remove": typeof takeoffCategories_remove;
  "takeoffCategories/search": typeof takeoffCategories_search;
  "takeoffCategories/shared": typeof takeoffCategories_shared;
  "takeoffCategories/update": typeof takeoffCategories_update;
  "takeoffs/addToTakeoffs": typeof takeoffs_addToTakeoffs;
  "takeoffs/get": typeof takeoffs_get;
  "takeoffs/list": typeof takeoffs_list;
  "takeoffs/remove": typeof takeoffs_remove;
  "takeoffs/rename": typeof takeoffs_rename;
  "takeoffs/save": typeof takeoffs_save;
  "takeoffs/shared": typeof takeoffs_shared;
  "tasks/add": typeof tasks_add;
  "tasks/appendNote": typeof tasks_appendNote;
  "tasks/deleteNote": typeof tasks_deleteNote;
  "tasks/list": typeof tasks_list;
  "tasks/listNotes": typeof tasks_listNotes;
  "tasks/remove": typeof tasks_remove;
  "tasks/shared": typeof tasks_shared;
  "tasks/update": typeof tasks_update;
  "tasks/updateStatus": typeof tasks_updateStatus;
  "tradeStages/add": typeof tradeStages_add;
  "tradeStages/list": typeof tradeStages_list;
  "tradeStages/remove": typeof tradeStages_remove;
  "tradeStages/reorder": typeof tradeStages_reorder;
  "tradeStages/shared": typeof tradeStages_shared;
  "tradeStages/update": typeof tradeStages_update;
  "trades/add": typeof trades_add;
  "trades/addMany": typeof trades_addMany;
  "trades/get": typeof trades_get;
  "trades/list": typeof trades_list;
  "trades/listXeroAssignments": typeof trades_listXeroAssignments;
  "trades/remove": typeof trades_remove;
  "trades/reorderTrades": typeof trades_reorderTrades;
  "trades/search": typeof trades_search;
  "trades/seed": typeof trades_seed;
  "trades/shared": typeof trades_shared;
  "trades/update": typeof trades_update;
  "units/list": typeof units_list;
  "units/seed": typeof units_seed;
  "users/create": typeof users_create;
  "users/list": typeof users_list;
  "users/remove": typeof users_remove;
  "users/setRoles": typeof users_setRoles;
  "users/update": typeof users_update;
  "vendors/add": typeof vendors_add;
  "vendors/addMany": typeof vendors_addMany;
  "vendors/get": typeof vendors_get;
  "vendors/list": typeof vendors_list;
  "vendors/remove": typeof vendors_remove;
  "vendors/search": typeof vendors_search;
  "vendors/seed": typeof vendors_seed;
  "vendors/shared": typeof vendors_shared;
  "vendors/update": typeof vendors_update;
  "web/banners": typeof web_banners;
  "web/leads": typeof web_leads;
  "web/projects": typeof web_projects;
  "web/shared": typeof web_shared;
  "websiteProjects/add": typeof websiteProjects_add;
  "websiteProjects/appendMedia": typeof websiteProjects_appendMedia;
  "websiteProjects/deleteMedia": typeof websiteProjects_deleteMedia;
  "websiteProjects/generateUploadUrl": typeof websiteProjects_generateUploadUrl;
  "websiteProjects/get": typeof websiteProjects_get;
  "websiteProjects/list": typeof websiteProjects_list;
  "websiteProjects/remove": typeof websiteProjects_remove;
  "websiteProjects/removeMediaEntry": typeof websiteProjects_removeMediaEntry;
  "websiteProjects/setMainImage": typeof websiteProjects_setMainImage;
  "websiteProjects/shared": typeof websiteProjects_shared;
  "websiteProjects/update": typeof websiteProjects_update;
  "xero/createAccount": typeof xero_createAccount;
  "xero/emailBillToXero": typeof xero_emailBillToXero;
  "xero/listAccounts": typeof xero_listAccounts;
  "xero/listTrackingOptions": typeof xero_listTrackingOptions;
  "xero/shared": typeof xero_shared;
  "xero/syncProjectFinancials": typeof xero_syncProjectFinancials;
  "xero/syncProjectFinancialsNow": typeof xero_syncProjectFinancialsNow;
  "xero/testAccounts": typeof xero_testAccounts;
  "xero/testConnection": typeof xero_testConnection;
  "xero/testProfitAndLoss": typeof xero_testProfitAndLoss;
  "xeroAccountActuals/apply": typeof xeroAccountActuals_apply;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
