/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as documentFolders_add from "../documentFolders/add.js";
import type * as documentFolders_get from "../documentFolders/get.js";
import type * as documentFolders_list from "../documentFolders/list.js";
import type * as documentFolders_remove from "../documentFolders/remove.js";
import type * as documentFolders_search from "../documentFolders/search.js";
import type * as documentFolders_seed from "../documentFolders/seed.js";
import type * as documentFolders_seedProjectFolders from "../documentFolders/seedProjectFolders.js";
import type * as documentFolders_shared from "../documentFolders/shared.js";
import type * as documentFolders_update from "../documentFolders/update.js";
import type * as fileStorage_deleteStorage from "../fileStorage/deleteStorage.js";
import type * as fileStorage_generateS3UploadUrl from "../fileStorage/generateS3UploadUrl.js";
import type * as fileStorage_generateUploadUrl from "../fileStorage/generateUploadUrl.js";
import type * as fileStorage_resolvePublicUrl from "../fileStorage/resolvePublicUrl.js";
import type * as inclusionCategories_add from "../inclusionCategories/add.js";
import type * as inclusionCategories_list from "../inclusionCategories/list.js";
import type * as inclusionCategories_remove from "../inclusionCategories/remove.js";
import type * as inclusionCategories_search from "../inclusionCategories/search.js";
import type * as inclusionCategories_shared from "../inclusionCategories/shared.js";
import type * as inclusionCategories_update from "../inclusionCategories/update.js";
import type * as inclusionVariants_add from "../inclusionVariants/add.js";
import type * as inclusionVariants_getUnit from "../inclusionVariants/getUnit.js";
import type * as inclusionVariants_listByInclusion from "../inclusionVariants/listByInclusion.js";
import type * as inclusionVariants_migrateImageBinariesToS3 from "../inclusionVariants/migrateImageBinariesToS3.js";
import type * as inclusionVariants_migrateImageHelpers from "../inclusionVariants/migrateImageHelpers.js";
import type * as inclusionVariants_migrateImagesToS3 from "../inclusionVariants/migrateImagesToS3.js";
import type * as inclusionVariants_remove from "../inclusionVariants/remove.js";
import type * as inclusionVariants_search from "../inclusionVariants/search.js";
import type * as inclusionVariants_shared from "../inclusionVariants/shared.js";
import type * as inclusionVariants_update from "../inclusionVariants/update.js";
import type * as inclusions_add from "../inclusions/add.js";
import type * as inclusions_backfillSearchText from "../inclusions/backfillSearchText.js";
import type * as inclusions_get from "../inclusions/get.js";
import type * as inclusions_list from "../inclusions/list.js";
import type * as inclusions_remove from "../inclusions/remove.js";
import type * as inclusions_search from "../inclusions/search.js";
import type * as inclusions_shared from "../inclusions/shared.js";
import type * as inclusions_update from "../inclusions/update.js";
import type * as lib_buildSearchText from "../lib/buildSearchText.js";
import type * as lib_checkIdentity from "../lib/checkIdentity.js";
import type * as lib_clerk from "../lib/clerk.js";
import type * as lib_logger from "../lib/logger.js";
import type * as lib_permissions from "../lib/permissions.js";
import type * as lib_toKebabCase from "../lib/toKebabCase.js";
import type * as locations_add from "../locations/add.js";
import type * as locations_get from "../locations/get.js";
import type * as locations_list from "../locations/list.js";
import type * as locations_remove from "../locations/remove.js";
import type * as locations_search from "../locations/search.js";
import type * as locations_seed from "../locations/seed.js";
import type * as locations_shared from "../locations/shared.js";
import type * as locations_update from "../locations/update.js";
import type * as materialColors_add from "../materialColors/add.js";
import type * as materialColors_get from "../materialColors/get.js";
import type * as materialColors_list from "../materialColors/list.js";
import type * as materialColors_remove from "../materialColors/remove.js";
import type * as materialColors_search from "../materialColors/search.js";
import type * as materialColors_seed from "../materialColors/seed.js";
import type * as materialColors_shared from "../materialColors/shared.js";
import type * as materialColors_update from "../materialColors/update.js";
import type * as materialItems_add from "../materialItems/add.js";
import type * as materialItems_listByVariant from "../materialItems/listByVariant.js";
import type * as materialItems_remove from "../materialItems/remove.js";
import type * as materialItems_shared from "../materialItems/shared.js";
import type * as materialItems_update from "../materialItems/update.js";
import type * as materialVariants_add from "../materialVariants/add.js";
import type * as materialVariants_addToProject from "../materialVariants/addToProject.js";
import type * as materialVariants_get from "../materialVariants/get.js";
import type * as materialVariants_listByMaterial from "../materialVariants/listByMaterial.js";
import type * as materialVariants_remove from "../materialVariants/remove.js";
import type * as materialVariants_search from "../materialVariants/search.js";
import type * as materialVariants_shared from "../materialVariants/shared.js";
import type * as materialVariants_update from "../materialVariants/update.js";
import type * as materials_add from "../materials/add.js";
import type * as materials_get from "../materials/get.js";
import type * as materials_list from "../materials/list.js";
import type * as materials_remove from "../materials/remove.js";
import type * as materials_search from "../materials/search.js";
import type * as materials_shared from "../materials/shared.js";
import type * as materials_update from "../materials/update.js";
import type * as migration_exportScheduleTemplates from "../migration/exportScheduleTemplates.js";
import type * as migration_importScheduleTemplate from "../migration/importScheduleTemplate.js";
import type * as permissions_getEffectiveForRoles from "../permissions/getEffectiveForRoles.js";
import type * as permissions_list from "../permissions/list.js";
import type * as permissions_listRoleNames from "../permissions/listRoleNames.js";
import type * as permissions_removeRole from "../permissions/removeRole.js";
import type * as permissions_upsertRole from "../permissions/upsertRole.js";
import type * as projectDocuments_create from "../projectDocuments/create.js";
import type * as projectDocuments_createFolder from "../projectDocuments/createFolder.js";
import type * as projectDocuments_deleteFolder from "../projectDocuments/deleteFolder.js";
import type * as projectDocuments_generateUploadUrl from "../projectDocuments/generateUploadUrl.js";
import type * as projectDocuments_listContents from "../projectDocuments/listContents.js";
import type * as projectDocuments_move from "../projectDocuments/move.js";
import type * as projectDocuments_remove from "../projectDocuments/remove.js";
import type * as projectDocuments_rename from "../projectDocuments/rename.js";
import type * as projectDocuments_renameFolder from "../projectDocuments/renameFolder.js";
import type * as projectDocuments_shared from "../projectDocuments/shared.js";
import type * as projectInclusions_add from "../projectInclusions/add.js";
import type * as projectInclusions_appendNote from "../projectInclusions/appendNote.js";
import type * as projectInclusions_backfillSearchText from "../projectInclusions/backfillSearchText.js";
import type * as projectInclusions_deleteNote from "../projectInclusions/deleteNote.js";
import type * as projectInclusions_list from "../projectInclusions/list.js";
import type * as projectInclusions_listNotes from "../projectInclusions/listNotes.js";
import type * as projectInclusions_migrateImageBinariesToS3 from "../projectInclusions/migrateImageBinariesToS3.js";
import type * as projectInclusions_migrateImageHelpers from "../projectInclusions/migrateImageHelpers.js";
import type * as projectInclusions_migrateImagesToS3 from "../projectInclusions/migrateImagesToS3.js";
import type * as projectInclusions_remove from "../projectInclusions/remove.js";
import type * as projectInclusions_search from "../projectInclusions/search.js";
import type * as projectInclusions_shared from "../projectInclusions/shared.js";
import type * as projectInclusions_update from "../projectInclusions/update.js";
import type * as projectOrders_add from "../projectOrders/add.js";
import type * as projectOrders_appendNote from "../projectOrders/appendNote.js";
import type * as projectOrders_deleteNote from "../projectOrders/deleteNote.js";
import type * as projectOrders_get from "../projectOrders/get.js";
import type * as projectOrders_list from "../projectOrders/list.js";
import type * as projectOrders_listNotes from "../projectOrders/listNotes.js";
import type * as projectOrders_listStatusHistory from "../projectOrders/listStatusHistory.js";
import type * as projectOrders_remove from "../projectOrders/remove.js";
import type * as projectOrders_shared from "../projectOrders/shared.js";
import type * as projectOrders_update from "../projectOrders/update.js";
import type * as projectServiceProviders_add from "../projectServiceProviders/add.js";
import type * as projectServiceProviders_listByProject from "../projectServiceProviders/listByProject.js";
import type * as projectServiceProviders_remove from "../projectServiceProviders/remove.js";
import type * as projects_add from "../projects/add.js";
import type * as projects_get from "../projects/get.js";
import type * as projects_list from "../projects/list.js";
import type * as projects_remove from "../projects/remove.js";
import type * as projects_search from "../projects/search.js";
import type * as projects_shared from "../projects/shared.js";
import type * as projects_update from "../projects/update.js";
import type * as quotations_add from "../quotations/add.js";
import type * as quotations_appendNote from "../quotations/appendNote.js";
import type * as quotations_approve from "../quotations/approve.js";
import type * as quotations_deleteNote from "../quotations/deleteNote.js";
import type * as quotations_generateUploadUrl from "../quotations/generateUploadUrl.js";
import type * as quotations_list from "../quotations/list.js";
import type * as quotations_listByProject from "../quotations/listByProject.js";
import type * as quotations_listByProjects from "../quotations/listByProjects.js";
import type * as quotations_listNotes from "../quotations/listNotes.js";
import type * as quotations_remove from "../quotations/remove.js";
import type * as quotations_search from "../quotations/search.js";
import type * as quotations_shared from "../quotations/shared.js";
import type * as quotations_update from "../quotations/update.js";
import type * as scheduleStages_add from "../scheduleStages/add.js";
import type * as scheduleStages_backfillOffsetDays from "../scheduleStages/backfillOffsetDays.js";
import type * as scheduleStages_backfillOrder from "../scheduleStages/backfillOrder.js";
import type * as scheduleStages_clearDependency from "../scheduleStages/clearDependency.js";
import type * as scheduleStages_listByTemplate from "../scheduleStages/listByTemplate.js";
import type * as scheduleStages_remove from "../scheduleStages/remove.js";
import type * as scheduleStages_reorder from "../scheduleStages/reorder.js";
import type * as scheduleStages_shared from "../scheduleStages/shared.js";
import type * as scheduleStages_update from "../scheduleStages/update.js";
import type * as scheduleStages_updateOffset from "../scheduleStages/updateOffset.js";
import type * as scheduleTasks_add from "../scheduleTasks/add.js";
import type * as scheduleTasks_backfillOffsetDays from "../scheduleTasks/backfillOffsetDays.js";
import type * as scheduleTasks_backfillOrder from "../scheduleTasks/backfillOrder.js";
import type * as scheduleTasks_clearDependency from "../scheduleTasks/clearDependency.js";
import type * as scheduleTasks_listByStage from "../scheduleTasks/listByStage.js";
import type * as scheduleTasks_listByTemplate from "../scheduleTasks/listByTemplate.js";
import type * as scheduleTasks_remove from "../scheduleTasks/remove.js";
import type * as scheduleTasks_reorder from "../scheduleTasks/reorder.js";
import type * as scheduleTasks_shared from "../scheduleTasks/shared.js";
import type * as scheduleTasks_update from "../scheduleTasks/update.js";
import type * as scheduleTasks_updateDuration from "../scheduleTasks/updateDuration.js";
import type * as scheduleTasks_updateOffset from "../scheduleTasks/updateOffset.js";
import type * as scheduleTemplates_add from "../scheduleTemplates/add.js";
import type * as scheduleTemplates_get from "../scheduleTemplates/get.js";
import type * as scheduleTemplates_list from "../scheduleTemplates/list.js";
import type * as scheduleTemplates_remove from "../scheduleTemplates/remove.js";
import type * as scheduleTemplates_search from "../scheduleTemplates/search.js";
import type * as scheduleTemplates_seed from "../scheduleTemplates/seed.js";
import type * as scheduleTemplates_shared from "../scheduleTemplates/shared.js";
import type * as scheduleTemplates_update from "../scheduleTemplates/update.js";
import type * as serviceProviders_add from "../serviceProviders/add.js";
import type * as serviceProviders_backfillSearchText from "../serviceProviders/backfillSearchText.js";
import type * as serviceProviders_get from "../serviceProviders/get.js";
import type * as serviceProviders_list from "../serviceProviders/list.js";
import type * as serviceProviders_remove from "../serviceProviders/remove.js";
import type * as serviceProviders_search from "../serviceProviders/search.js";
import type * as serviceProviders_seed from "../serviceProviders/seed.js";
import type * as serviceProviders_shared from "../serviceProviders/shared.js";
import type * as serviceProviders_update from "../serviceProviders/update.js";
import type * as trades_add from "../trades/add.js";
import type * as trades_get from "../trades/get.js";
import type * as trades_list from "../trades/list.js";
import type * as trades_remove from "../trades/remove.js";
import type * as trades_search from "../trades/search.js";
import type * as trades_seed from "../trades/seed.js";
import type * as trades_shared from "../trades/shared.js";
import type * as trades_update from "../trades/update.js";
import type * as units_list from "../units/list.js";
import type * as units_seed from "../units/seed.js";
import type * as vendors_add from "../vendors/add.js";
import type * as vendors_get from "../vendors/get.js";
import type * as vendors_list from "../vendors/list.js";
import type * as vendors_remove from "../vendors/remove.js";
import type * as vendors_search from "../vendors/search.js";
import type * as vendors_seed from "../vendors/seed.js";
import type * as vendors_shared from "../vendors/shared.js";
import type * as vendors_update from "../vendors/update.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "documentFolders/add": typeof documentFolders_add;
  "documentFolders/get": typeof documentFolders_get;
  "documentFolders/list": typeof documentFolders_list;
  "documentFolders/remove": typeof documentFolders_remove;
  "documentFolders/search": typeof documentFolders_search;
  "documentFolders/seed": typeof documentFolders_seed;
  "documentFolders/seedProjectFolders": typeof documentFolders_seedProjectFolders;
  "documentFolders/shared": typeof documentFolders_shared;
  "documentFolders/update": typeof documentFolders_update;
  "fileStorage/deleteStorage": typeof fileStorage_deleteStorage;
  "fileStorage/generateS3UploadUrl": typeof fileStorage_generateS3UploadUrl;
  "fileStorage/generateUploadUrl": typeof fileStorage_generateUploadUrl;
  "fileStorage/resolvePublicUrl": typeof fileStorage_resolvePublicUrl;
  "inclusionCategories/add": typeof inclusionCategories_add;
  "inclusionCategories/list": typeof inclusionCategories_list;
  "inclusionCategories/remove": typeof inclusionCategories_remove;
  "inclusionCategories/search": typeof inclusionCategories_search;
  "inclusionCategories/shared": typeof inclusionCategories_shared;
  "inclusionCategories/update": typeof inclusionCategories_update;
  "inclusionVariants/add": typeof inclusionVariants_add;
  "inclusionVariants/getUnit": typeof inclusionVariants_getUnit;
  "inclusionVariants/listByInclusion": typeof inclusionVariants_listByInclusion;
  "inclusionVariants/migrateImageBinariesToS3": typeof inclusionVariants_migrateImageBinariesToS3;
  "inclusionVariants/migrateImageHelpers": typeof inclusionVariants_migrateImageHelpers;
  "inclusionVariants/migrateImagesToS3": typeof inclusionVariants_migrateImagesToS3;
  "inclusionVariants/remove": typeof inclusionVariants_remove;
  "inclusionVariants/search": typeof inclusionVariants_search;
  "inclusionVariants/shared": typeof inclusionVariants_shared;
  "inclusionVariants/update": typeof inclusionVariants_update;
  "inclusions/add": typeof inclusions_add;
  "inclusions/backfillSearchText": typeof inclusions_backfillSearchText;
  "inclusions/get": typeof inclusions_get;
  "inclusions/list": typeof inclusions_list;
  "inclusions/remove": typeof inclusions_remove;
  "inclusions/search": typeof inclusions_search;
  "inclusions/shared": typeof inclusions_shared;
  "inclusions/update": typeof inclusions_update;
  "lib/buildSearchText": typeof lib_buildSearchText;
  "lib/checkIdentity": typeof lib_checkIdentity;
  "lib/clerk": typeof lib_clerk;
  "lib/logger": typeof lib_logger;
  "lib/permissions": typeof lib_permissions;
  "lib/toKebabCase": typeof lib_toKebabCase;
  "locations/add": typeof locations_add;
  "locations/get": typeof locations_get;
  "locations/list": typeof locations_list;
  "locations/remove": typeof locations_remove;
  "locations/search": typeof locations_search;
  "locations/seed": typeof locations_seed;
  "locations/shared": typeof locations_shared;
  "locations/update": typeof locations_update;
  "materialColors/add": typeof materialColors_add;
  "materialColors/get": typeof materialColors_get;
  "materialColors/list": typeof materialColors_list;
  "materialColors/remove": typeof materialColors_remove;
  "materialColors/search": typeof materialColors_search;
  "materialColors/seed": typeof materialColors_seed;
  "materialColors/shared": typeof materialColors_shared;
  "materialColors/update": typeof materialColors_update;
  "materialItems/add": typeof materialItems_add;
  "materialItems/listByVariant": typeof materialItems_listByVariant;
  "materialItems/remove": typeof materialItems_remove;
  "materialItems/shared": typeof materialItems_shared;
  "materialItems/update": typeof materialItems_update;
  "materialVariants/add": typeof materialVariants_add;
  "materialVariants/addToProject": typeof materialVariants_addToProject;
  "materialVariants/get": typeof materialVariants_get;
  "materialVariants/listByMaterial": typeof materialVariants_listByMaterial;
  "materialVariants/remove": typeof materialVariants_remove;
  "materialVariants/search": typeof materialVariants_search;
  "materialVariants/shared": typeof materialVariants_shared;
  "materialVariants/update": typeof materialVariants_update;
  "materials/add": typeof materials_add;
  "materials/get": typeof materials_get;
  "materials/list": typeof materials_list;
  "materials/remove": typeof materials_remove;
  "materials/search": typeof materials_search;
  "materials/shared": typeof materials_shared;
  "materials/update": typeof materials_update;
  "migration/exportScheduleTemplates": typeof migration_exportScheduleTemplates;
  "migration/importScheduleTemplate": typeof migration_importScheduleTemplate;
  "permissions/getEffectiveForRoles": typeof permissions_getEffectiveForRoles;
  "permissions/list": typeof permissions_list;
  "permissions/listRoleNames": typeof permissions_listRoleNames;
  "permissions/removeRole": typeof permissions_removeRole;
  "permissions/upsertRole": typeof permissions_upsertRole;
  "projectDocuments/create": typeof projectDocuments_create;
  "projectDocuments/createFolder": typeof projectDocuments_createFolder;
  "projectDocuments/deleteFolder": typeof projectDocuments_deleteFolder;
  "projectDocuments/generateUploadUrl": typeof projectDocuments_generateUploadUrl;
  "projectDocuments/listContents": typeof projectDocuments_listContents;
  "projectDocuments/move": typeof projectDocuments_move;
  "projectDocuments/remove": typeof projectDocuments_remove;
  "projectDocuments/rename": typeof projectDocuments_rename;
  "projectDocuments/renameFolder": typeof projectDocuments_renameFolder;
  "projectDocuments/shared": typeof projectDocuments_shared;
  "projectInclusions/add": typeof projectInclusions_add;
  "projectInclusions/appendNote": typeof projectInclusions_appendNote;
  "projectInclusions/backfillSearchText": typeof projectInclusions_backfillSearchText;
  "projectInclusions/deleteNote": typeof projectInclusions_deleteNote;
  "projectInclusions/list": typeof projectInclusions_list;
  "projectInclusions/listNotes": typeof projectInclusions_listNotes;
  "projectInclusions/migrateImageBinariesToS3": typeof projectInclusions_migrateImageBinariesToS3;
  "projectInclusions/migrateImageHelpers": typeof projectInclusions_migrateImageHelpers;
  "projectInclusions/migrateImagesToS3": typeof projectInclusions_migrateImagesToS3;
  "projectInclusions/remove": typeof projectInclusions_remove;
  "projectInclusions/search": typeof projectInclusions_search;
  "projectInclusions/shared": typeof projectInclusions_shared;
  "projectInclusions/update": typeof projectInclusions_update;
  "projectOrders/add": typeof projectOrders_add;
  "projectOrders/appendNote": typeof projectOrders_appendNote;
  "projectOrders/deleteNote": typeof projectOrders_deleteNote;
  "projectOrders/get": typeof projectOrders_get;
  "projectOrders/list": typeof projectOrders_list;
  "projectOrders/listNotes": typeof projectOrders_listNotes;
  "projectOrders/listStatusHistory": typeof projectOrders_listStatusHistory;
  "projectOrders/remove": typeof projectOrders_remove;
  "projectOrders/shared": typeof projectOrders_shared;
  "projectOrders/update": typeof projectOrders_update;
  "projectServiceProviders/add": typeof projectServiceProviders_add;
  "projectServiceProviders/listByProject": typeof projectServiceProviders_listByProject;
  "projectServiceProviders/remove": typeof projectServiceProviders_remove;
  "projects/add": typeof projects_add;
  "projects/get": typeof projects_get;
  "projects/list": typeof projects_list;
  "projects/remove": typeof projects_remove;
  "projects/search": typeof projects_search;
  "projects/shared": typeof projects_shared;
  "projects/update": typeof projects_update;
  "quotations/add": typeof quotations_add;
  "quotations/appendNote": typeof quotations_appendNote;
  "quotations/approve": typeof quotations_approve;
  "quotations/deleteNote": typeof quotations_deleteNote;
  "quotations/generateUploadUrl": typeof quotations_generateUploadUrl;
  "quotations/list": typeof quotations_list;
  "quotations/listByProject": typeof quotations_listByProject;
  "quotations/listByProjects": typeof quotations_listByProjects;
  "quotations/listNotes": typeof quotations_listNotes;
  "quotations/remove": typeof quotations_remove;
  "quotations/search": typeof quotations_search;
  "quotations/shared": typeof quotations_shared;
  "quotations/update": typeof quotations_update;
  "scheduleStages/add": typeof scheduleStages_add;
  "scheduleStages/backfillOffsetDays": typeof scheduleStages_backfillOffsetDays;
  "scheduleStages/backfillOrder": typeof scheduleStages_backfillOrder;
  "scheduleStages/clearDependency": typeof scheduleStages_clearDependency;
  "scheduleStages/listByTemplate": typeof scheduleStages_listByTemplate;
  "scheduleStages/remove": typeof scheduleStages_remove;
  "scheduleStages/reorder": typeof scheduleStages_reorder;
  "scheduleStages/shared": typeof scheduleStages_shared;
  "scheduleStages/update": typeof scheduleStages_update;
  "scheduleStages/updateOffset": typeof scheduleStages_updateOffset;
  "scheduleTasks/add": typeof scheduleTasks_add;
  "scheduleTasks/backfillOffsetDays": typeof scheduleTasks_backfillOffsetDays;
  "scheduleTasks/backfillOrder": typeof scheduleTasks_backfillOrder;
  "scheduleTasks/clearDependency": typeof scheduleTasks_clearDependency;
  "scheduleTasks/listByStage": typeof scheduleTasks_listByStage;
  "scheduleTasks/listByTemplate": typeof scheduleTasks_listByTemplate;
  "scheduleTasks/remove": typeof scheduleTasks_remove;
  "scheduleTasks/reorder": typeof scheduleTasks_reorder;
  "scheduleTasks/shared": typeof scheduleTasks_shared;
  "scheduleTasks/update": typeof scheduleTasks_update;
  "scheduleTasks/updateDuration": typeof scheduleTasks_updateDuration;
  "scheduleTasks/updateOffset": typeof scheduleTasks_updateOffset;
  "scheduleTemplates/add": typeof scheduleTemplates_add;
  "scheduleTemplates/get": typeof scheduleTemplates_get;
  "scheduleTemplates/list": typeof scheduleTemplates_list;
  "scheduleTemplates/remove": typeof scheduleTemplates_remove;
  "scheduleTemplates/search": typeof scheduleTemplates_search;
  "scheduleTemplates/seed": typeof scheduleTemplates_seed;
  "scheduleTemplates/shared": typeof scheduleTemplates_shared;
  "scheduleTemplates/update": typeof scheduleTemplates_update;
  "serviceProviders/add": typeof serviceProviders_add;
  "serviceProviders/backfillSearchText": typeof serviceProviders_backfillSearchText;
  "serviceProviders/get": typeof serviceProviders_get;
  "serviceProviders/list": typeof serviceProviders_list;
  "serviceProviders/remove": typeof serviceProviders_remove;
  "serviceProviders/search": typeof serviceProviders_search;
  "serviceProviders/seed": typeof serviceProviders_seed;
  "serviceProviders/shared": typeof serviceProviders_shared;
  "serviceProviders/update": typeof serviceProviders_update;
  "trades/add": typeof trades_add;
  "trades/get": typeof trades_get;
  "trades/list": typeof trades_list;
  "trades/remove": typeof trades_remove;
  "trades/search": typeof trades_search;
  "trades/seed": typeof trades_seed;
  "trades/shared": typeof trades_shared;
  "trades/update": typeof trades_update;
  "units/list": typeof units_list;
  "units/seed": typeof units_seed;
  "vendors/add": typeof vendors_add;
  "vendors/get": typeof vendors_get;
  "vendors/list": typeof vendors_list;
  "vendors/remove": typeof vendors_remove;
  "vendors/search": typeof vendors_search;
  "vendors/seed": typeof vendors_seed;
  "vendors/shared": typeof vendors_shared;
  "vendors/update": typeof vendors_update;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
